### ISSUE TITLE
Adicionar README

### ISSUE THREAD

**Issue by Takeshi-mi** [Everton-Leon/Aposentadoria#1]
Oi Everton, vi que está postando vários projetinhos teus. 
Tenho uma sugestão. Adiciona o README falando um pouco do projeto, do problema que o programa está resolvendo e com prints do output(no caso desse que o resultado sai no terminal) ou prints da interface. 

Aqui vai um site bem legal para te ajudar com a escrita. 

[Como-escrever-um-bom-readme](https://www.alura.com.br/artigos/escrever-bom-readme)

**Comment by Everton-Leon** [comment]
Oii, obrigado pela dica, vou adicionar sim. Não adicionei antes por que não
tava aparecendo a linguagem que os projetos estão. Mas vou começar a
adicionar novo, obrigado.

Em seg., 30 de jan. de 2023 21:05, Takeshi Miura ***@***.***>
escreveu:
